# Generated by Django 5.2 on 2025-06-11 16:32

import GreenLeafAPI.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to=GreenLeafAPI.models.plant_upload_to)),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('habitat', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_by', models.ForeignKey(default='no user', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_image', models.ImageField(blank=True, null=True, upload_to=GreenLeafAPI.models.observation_upload_to)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=250)),
                ('note', models.CharField(blank=True, max_length=3000, null=True)),
                ('created_by', models.ForeignKey(default='no user', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('related_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GreenLeafAPI.plantmodel')),
            ],
        ),
    ]
